version: "3.8"

services:
  # Frontend Builder: React 애플리케이션 빌드
  frontend-builder:
    build:
      context: ./fe-rian
      dockerfile: Dockerfile
    volumes:
      - frontend-build:/app/build  # 빌드 결과를 볼륨에 저장
    command: ["npm", "run", "build"]  # 빌드 후 종료
    working_dir: /app  # 빌드를 실행할 작업 디렉토리 설정

  # Nginx: React 앱을 제공하는 Nginx 서버
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - frontend-build:/usr/share/nginx/html  # 빌드 결과를 nginx에서 참조
    depends_on:
      - frontend-builder  # frontend-builder가 먼저 빌드를 완료해야 nginx가 실행됨

volumes:
  frontend-build:  # Named Volume 정의
